stages:
  - test
  - build
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - ldd --version ldd  # For debugging
  - python3.8 --version  # For debugging
  - python3.10 --version  # For debugging
  - python3.8 -m pip install --upgrade pip
  - python3.8 -m pip install virtualenv
  - python3.8 -m venv ./venv
  - source venv/bin/activate
  - python -m pip install build
  - python -m pip install pytest
  - python -m pip install auditwheel
  - python -m pip install twine
  - cat $PYPIRC > /root/.pypirc

test:
  when: manual
  script:
    - pip install .
    - python -m pytest
    - python setup.py build
    - python -m build

build_38_manylinux1_x86_64:
  image: quay.io/pypa/manylinux2014_x86_64:latest
  # when: manual
  stage: build
  only:
    - tags
  script:
    - python -m build
  artifacts:
    paths:
      - dist/*.whl

publish_38_manylinux1_x86_64:
  image: quay.io/pypa/manylinux2014_x86_64:latest
  # when: manual
  stage: publish
  only:
  - tags
  script:
    - python -m auditwheel repair $(ls dist/*.whl)
    - python -m twine upload -r pypi $(ls wheelhouse/*.whl) --verbose
  needs:
    - job: build_38_manylinux1_x86_64
      artifacts: true
